### PR TITLE
replace docs with links

### PR DESCRIPTION
**Pull request by nialexsan**
Closes: #???

## Description

replaces docs content with links to their new location in https://github.com/onflow/docs
using script from https://github.com/onflow/docs/pull/46/files#diff-c664086afba767b573a654a57f324cee7c36fe1e9b7a1a02627c642577897871

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-ft/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels 

- [ ] Update the version in package.json when there is a change in the smart contracts

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]

**Review by bthaile — APPROVED** [review]
lgtm

**Comment by joshuahannan** [comment]
Yeah, I'm starting to think that this might not be a good idea. These docs are just auto-generated from the comments in the code, so it doesn't seem like it is very efficient to have to generate them and then copy them over to another repo. It would be much easier if they could just live here and then could get picked up by the docs site

**Comment by joshuahannan** [comment]
All docs in this repo except for the main README are autogenerated

**Comment by joshuahannan** [comment]
I'm going to close this PR

**Pull request closed without merging**
