### PR TITLE
Add functionality to switchboard to link receiver capabilities to different receiver types

### PR DESCRIPTION
**Pull request by alilloig**
Closes: #102 #104
(both issues are the same, 102 was raised before, 104 explains really good the problem)

## Description

Includes a new method on the switchboard `addNewVaultWrapper(capability: Capability<&{FungibleToken.Receiver}>, type: Type)` that allows to link a receiver to the switchboard that will be able to receive a deposit from a different type of receiver than the linked one
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [standards mentioned here](https://github.com/onflow/flow-ft/blob/master/CONTRIBUTING.md#styleguides).
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels 
- [x] Update the version in package.json when there is a change in the smart contracts

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]
looks great!

**Comment by bluesign** [comment]
When do we plan to release switchboard?

**Comment by alilloig** [comment]
Hi @bluesign !! Couple of weeks ago we uploaded it to testnet in order to get it into mainnet asap. The lacking of this feature was noticed by @bjartek and another user. Once this get merged and updated on testnet probably we can deploy it on mainnet, I'll love to do it next week before the holidays.

**Comment by alilloig** [comment]
@satyamakgec @sisyphusSmiling this is running okey locally, have you ever run into this issue?

Screenshot 2022-12-15 at 20 26 13

**Comment by sisyphusSmiling** [comment]
@alilloig I was able to recreate this locally by updating `flow-cli`. Looks like the GH Action grabs the latest flow-cli release and runs the test. Taking a look at recent issues in the flow-cli repo, I see [an issue](https://github.com/onflow/flow-cli/issues/737) that versions 0.42.0 and above are incompatible with `flow-js-testing`.

I've updated the `flow-cli` install command to include 0.41.2 as recommended by @sideninja in [this issue](https://github.com/onflow/flow-cli/issues/737), and it looks like ci is now passing.

**Pull request merged**
