### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by turbolent**
Some improvements:

- Change the return types of `ExampleToken.Vault`'s `withdraw` and `ExampleToken.createEmptyVault` to the more specific type `Vault`
- Use docstring literals (`///`) for documentation comments of types, fields, and functions
- Use a fixed-point literal where possible (e.g. `0.0` instead of `UFix64(0)`)

I can't test this right now because of:

```$ go get                                                                                                                                        
go: github.com/dapperlabs/flow-emulator@v0.10.0 requires
	github.com/onflow/flow/protobuf/go/flow@v0.1.5-0.20200806013300-5011e9d6a292: invalid version: unknown revision 5011e9d6a292
```

Any ideas @psiemens ?

### CODE REVIEW

**Review by MaxStalker — APPROVED** [review]
Looks good to me 👍 

Are docstrings supported now or this is future-proof edit? :)

**Review by joshuahannan — APPROVED** [review]

**Comment by turbolent** [comment]
Docstrings are supported, as in, they're part of the AST, and are used by the language server in completions. We plan to add more tooling, such as a documentation generator

**Comment by turbolent** [comment]
@joshuahannan are you able to test this?

**Comment by joshuahannan** [comment]
@turbolent yeah I was able to run the tests locally and they passed after I remove the zero balance deposit test

**Comment by turbolent** [comment]
@joshuahannan perfect, thanks! Could you please commit the removal or adjusted version of the zero balance deposit test?

**Comment by joshuahannan** [comment]
yep, I did it in d14def3

**Comment by turbolent** [comment]
Perfect! Sorry, didn't see it 👍

**Pull request merged**
