### PR TITLE
Workflow for automatic deployment of npm package.

### PR DESCRIPTION
**Pull request by satyamakgec**
Closes: #69 

## Description

Allow publishing a package to the npm using the changeset.

- Any changes merged in the master will lead to the release of a new version of the `@onflow/flow-ft` package.
______

For contributor use:

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/flow-nft/blob/master/CONTRIBUTING.md#styleguides).
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by joshuahannan** [comment]
@satyamakgec Can you add a description to the PR for what this is doing?

**Comment by satyamakgec** [comment]
> @satyamakgec Can you add a description to the PR for what this is doing?

Very sorry old habits! It is added.

**Comment by justinbarry** [comment]
We have been using [changeset](https://github.com/changesets/changesets) package from Atlassian to do handle this and it has worked out wonderfully. It is also automatable to various degrees. See [here](https://github.com/changesets/changesets/blob/main/docs/automating-changesets.md).

**Comment by satyamakgec** [comment]
@justinbarry @JeffreyDoyle can you please guys take another look again and approve it.

**Review by justinbarry — APPROVED** [review]
LGTM

**Review by joshuahannan — APPROVED** [review]

**Pull request merged**
